#ifndef PUBLIC_H
#define PUBLIC_H

enum EnMsgType
{
    LOGIN_MSG = 1,
    LOGIN_MSG_ACK,

    REG_MSG,
    REG_MSG_ACK,

    CHAT_PRIVATE_MSG,
    CHAT_GROUP_MSG,

    FRIEND_ADD_MSG,
    FRIEND_DELETE_MSG,
    FRIEND_QUERY_MSG,
    FRIEND_QUERY_MSG_ACK,

    GROUP_CREATE_MSG,
    GROUP_REMOVE_MSG,
    GROUP_SHOW_MSG,
    GROUP_CREATE_MSG_ACK,
    GROUP_SHOW_MSG_ACK,
    
    GROUP_JOIN_MSG,
    GROUP_JOIN_MSG_ACK,
    GROUP_QUIT_MSG,
    GROUP_QUIT_MSG_ACK,

    USER_GROUP_QUERY_MSG,
    USER_GROUP_QUERY_MSG_ACK,

    QUIT_MSG,
};

#endif